SET DATABASE SQL SYNTAX ORA TRUE;


CREATE TABLE ORSS_MESSAGE_DETAILS
  (
    "KEY"                 VARCHAR2(800 BYTE) NOT NULL ,
    "KEYTYPE"             VARCHAR2(50 BYTE) NOT NULL ,
    "PROTOCOL_MESSAGEID"  VARCHAR2(100 BYTE) NOT NULL ,
    "CONVERSATION_ID"     VARCHAR2(100 BYTE) NOT NULL ,
    "NIMS_ID"             VARCHAR2(30 BYTE),
    "ESTIMATE_NUMBER"     VARCHAR2(15 BYTE),
    "CONTRACT_NUMBER"     VARCHAR2(15 BYTE),
    "SUPPLIER_ID"         VARCHAR2(30 BYTE),
    "MESSAGE_CODE"        VARCHAR2(30 BYTE),
    "NIMS_SLIP_NUMBER"    VARCHAR2(15 BYTE),
    "SUPPLIER_REF_NUMBER" VARCHAR2(15 BYTE),
    "DIRECTION"           VARCHAR2(15 BYTE),
    "MESSAGE_TIMESTAMP" TIMESTAMP (9),
    "RECEIPT_TIMESTAMP" TIMESTAMP (9),
    "STATUS"           VARCHAR2(100 BYTE),
    "EXCEPTIONMESSAGE" VARCHAR2(800 BYTE),
    "PAYLOAD" CLOB NOT NULL ,
    "RESUBMITTED_DATETIME" TIMESTAMP (9),
    "SENDER_MESSAGEID"   VARCHAR2(50 BYTE),
    "RECEIVER_MESSAGEID" VARCHAR2(50 BYTE),
	"SITE_ID" VARCHAR2(80 BYTE), 
	"MODIFIED_TIMESTAMP_GMT" TIMESTAMP (9),
    CONSTRAINT "E537MD_PK" PRIMARY KEY ("KEY", "KEYTYPE", "PROTOCOL_MESSAGEID")
);

 

CREATE TABLE ORSS_RECEIPT_CORRELATION
  (
    "KEY"                VARCHAR2(800 BYTE) NOT NULL ,
    "KEYTYPE"            VARCHAR2(50 BYTE) NOT NULL ,
    "PROTOCOL_MESSAGEID" VARCHAR2(100 BYTE) NOT NULL ,
    "LET" TIMESTAMP (9) NOT NULL ,
    "RESUBMISSION_COUNT"    NUMBER(10,0),
    "RESUBMISSION_INTERVAL" NUMBER(10,0),
    "STATUS"                VARCHAR2(50 BYTE) NOT NULL ,
    "DIRECTION"             VARCHAR2(15 BYTE) NOT NULL ,
    "E2EVALUES"             VARCHAR2(1000 BYTE),
    CONSTRAINT "E537DRC_PK" PRIMARY KEY ("KEY", "KEYTYPE", "PROTOCOL_MESSAGEID")
);



CREATE TABLE ORSS_SUPPLIERID
  (
    "SUPPLIER_ID" VARCHAR2(30 BYTE) NOT NULL ,
    "USER_ORSS"   VARCHAR2(30 BYTE),
    "INSERTEDTIME" TIMESTAMP (9)
  );

 


CREATE TABLE ORSS_SUPPORT_TOOL_USERS 
   (	"USER_NAME" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"PASS_WORD" CLOB, 
	"STATUS" NUMBER(3,0) DEFAULT 1, 
	"ROLE" VARCHAR2(20 BYTE)
   );
   
ALTER TABLE ORSS_SUPPORT_TOOL_USERS ADD UNIQUE ("USER_NAME");





 CREATE TABLE ORSS_PROPERTY
   (	"PROPERTY_NAME" VARCHAR2(800 BYTE), 
	"PROPERTY_VALUE" VARCHAR2(800 BYTE)
   );


CREATE TABLE ORSS_MESSAGE_CODE
   (	"MESSAGE_CODE" VARCHAR2(30 BYTE) NOT NULL
   );
   
  


CREATE TABLE AUDIT_LOGS 
   (	"USER_NAME" VARCHAR2(40 BYTE), 
	"ID" VARCHAR2(100 BYTE), 
	"SESSION_ID" VARCHAR2(100 BYTE), 
	"SIGN_IN" TIMESTAMP (6), 
	"SIGN_OUT" TIMESTAMP (6), 
	"SITE_ID" VARCHAR2(30 BYTE), 
	"RESUBMIT_COUNT" VARCHAR2(5 BYTE) DEFAULT 0, 
	"MESSAGE_DELETED_COUNT" VARCHAR2(5 BYTE) DEFAULT 0,
   );
	
   
 	  ALTER TABLE AUDIT_LOGS ADD PRIMARY KEY ("ID");

   